import React from 'react'

const Ourwhy = () => {
    return (
        <div style={{ textAlign: "center"}} >
            <br />
            <br />
            <h1>Our why</h1>
            <br />
            <h5>Excerpt from Evicted: Poverty and Profit in American City by Desmond Matthew</h5>
            <br />
            <h3>
The home is the center of life. It is a refuge from the grind of work, the pressure of school, and the menace of the streets. We say that at home, we can “be ourselves.” Everywhere else, we are someone else. At home, we remove our masks.
<br />
 The home is the wellspring of personhood. It is where our identity takes root and blossoms, where as children, we imagine, play, and question, and as adolescents, we retreat and try. As we grow older, we hope to settle into a place to raise a family or pursue work. When we try to understand ourselves, we often begin by considering the kind of home in which we were raised. <br /> 
 <br />
 In languages spoken all over the world, the word for “home” encompasses not just shelter but warmth, safety, family—the womb. The ancient Egyptian hieroglyph for “home” was often used in place of “mother.” 
The Chinese word jiā can mean both family and home. “Shelter” comes from two Old English words: scield (shield) and truma (troop), together forming the image of a family gathering itself within a protective shell. 1 The home remains the primary basis of life. It is where meals are shared, quiet habits formed, dreams confessed, traditions created. <br /> 
<br />
Civic life too begins at home, allowing us to plant roots and take ownership over our community, participate in local politics, and reach out to neighbors in a spirit of solidarity and generosity. “It is difficult to force a man out of himself and get him to take an interest in the affairs of the whole state,” 
<br />
Alexis de Tocqueville once observed. “But if it is a question of taking a road past his property, he sees at once that this small public matter has a bearing on his greatest private interests.” 2 It is only after we begin to see a street as our street, a public park as our park, a school as our school, that we can become engaged citizens, dedicating our time and resources for worthwhile causes: joining the Neighborhood Watch, volunteering to beautify a playground, or running for school board. Working on behalf of the common good is the engine of democracy, vital to our communities, cities, states—and, ultimately, the nation. It is “an outflow of the idealism and moralism of the American people,” wrote Gunnar Myrdal. 
<br />Some have called this impulse “love of country” or “patriotism” or the “American spirit.” But whatever its name, its foundation is the home. What else is a nation but a patchwork of cities and towns; cities and towns a patchwork of neighborhoods; and neighborhoods a patchwork of homes? <br /> 
<br />

America is supposed to be a place where you can better yourself, your family, and your community. But this is only possible if you have a stable home. When Scott was provided with an affordable apartment through the Guest House’s permanent housing program, he was able to stay off heroin, find meaningful work as a resident manager for homeless people, and begin striving for independence. He remains stably housed and sober. And then there are the Hinkstons. After Malik Jr. was born, Patrice and Doreen finally did move to Brownsville, Tennessee, a town of about 10,000. They found a nice three-bedroom place. Out of the rat hole, Patrice earned her GED, impressing her teacher so much that she was named Adult Learner of the Year. Patrice went on to enroll in a local community college, where she took online classes in computers and criminal justice, hoping to one day become a parole officer. She liked to half joke, “I got a lot of friends who are criminal who are going to need my help!” The persistence and brutality of American poverty can be disheartening, leaving us cynical about solutions. But as Scott and Patrice will tell you, a good home can serve as the sturdiest of footholds. When people have a place to live, they become better parents, workers, and citizens. If Arleen and Vanetta didn’t have to dedicate 70 or 80 percent of their income to rent, they could keep their kids fed and clothed and off the streets. <br /> 
<br />
They could settle down in one neighborhood and enroll their children in one school, providing them the opportunity to form long-lasting relationships with friends, role models, and teachers. They could start a savings account or buy their children toys and books, perhaps even a home computer. The time and emotional energy they spent making rent, delaying eviction, or finding another place to live when homeless could instead be spent on things that enriched their lives: community college classes, exercise, finding a good job, maybe a good man too. But our current state of affairs “reduces to poverty people born for better things.” 3 For almost a century, there has been broad consensus in America that families should spend no more than 30 percent of their income on housing. 5 Until recently, most renting families met this goal. But times have changed—in Milwaukee and across America. Every year in this country, people are evicted from their homes not by the tens of thousands or even the hundreds of thousands but by the millions. 6 — Until recently, we simply didn’t know how immense this problem was, or how serious the consequences, unless we had suffered them ourselves. For years, social scientists, journalists, and policymakers all but ignored eviction, making it one of the least studied processes affecting the lives of poor families. But new data and methods have allowed us to measure the prevalence of eviction and document its effects. <br /> 
<br />
We have learned that eviction is commonplace in poor neighborhoods and that it exacts a heavy toll on families, communities, and children. Residential stability begets a kind of psychological stability, which allows people to invest in their home and social relationships. It begets school stability, which increases the chances that children will excel and graduate. And it begets community stability, which encourages neighbors to form strong bonds and take care of their block. 7 But poor families enjoy little of that because they are evicted at such high rates. That low-income families move often is well known. Why they do is a question that has puzzled researchers and policymakers because they have overlooked the frequency of eviction in disadvantaged neighborhoods. 8 Between 2009 and 2011, roughly a quarter of all moves undertaken by Milwaukee’s poorest renters were involuntary. Once you account for those dislocations (eviction, landlord foreclosure), low-income households move at a similar rate as everyone else. 9 If you study eviction court records in other cities, you arrive at similarly startling numbers. Jackson County, Missouri, which includes half of Kansas City, saw 19 formal evictions a day between 2009 and 2013. New York City courts saw almost 80 nonpayment evictions a day in 2012. That same year, 1 in 9 occupied rental households in Cleveland, and 1 in 13 in Chicago, were summoned to eviction court. 10 Instability is not inherent to poverty. Poor families move so much because they are forced to. Along with instability, eviction also causes loss. Families lose not only their home, school, and neighborhood but also their possessions: furniture, clothes, books. It takes a good amount of money and time to establish a home. 

<br /> 
<br />
Eviction can erase all that. Arleen lost everything. Larraine and Scott too. Eviction can cause workers to lose their jobs. The likelihood of being laid off is roughly 15 percent higher for workers who have experienced an eviction. If housing instability leads to employment instability, it is because the stress and consuming nature of being forced from your home wreak havoc on people’s work performance. 11 Often, evicted families also lose the opportunity to benefit from public housing because Housing Authorities count evictions and unpaid debt as strikes when reviewing applications. And so people who have the greatest need for housing assistance—the rent-burdened and evicted—are systematically denied it. 12 This—the loss of your possessions, job, home, and access to government aid—helps explain why eviction has such a pronounced effect on what social scientists call “material hardship,” a measure of the texture of scarcity. Material hardship assesses, say, whether families experience hunger or sickness because food or medical care is financially out of reach or go without heat, electricity, or a phone because they can’t afford those things. 
<br /> 
<br />
The year after eviction, families experience 20 percent higher levels of material hardship than similar families who were not evicted. They go without food. They endure illness and cold. Evicted families continue to have higher levels of material hardship at least two years after the event. 13 These families are often compelled to accept substandard housing conditions. In Milwaukee, renters whose previous move was involuntary were 25 percent more likely to experience long-term housing problems than similar renters who moved under less trying circumstances. 13 And families forced from their homes are pushed into undesirable parts of the city, moving from poor neighborhoods into even poorer ones; from crime-filled areas into still more dangerous ones. Arleen’s favorite place was nested in a working-class black neighborhood. <br />
<br />
 After the city condemned it and forced her out, she moved into an apartment complex teeming with drug dealers. Even after controlling for a host of important factors, families who experience a forced move relocate to worse neighborhoods than those who move under less demanding circumstances. 15 Concentrated poverty and violence inflict their own wounds, since neighborhoods determine so much about your life, from the kinds of job opportunities you have to the kinds of schools your children attend. 16 Then there is the toll eviction takes on a person’s spirit. The violence of displacement can drive people to depression and, in extreme cases, even suicide. One in two recently evicted mothers reports multiple symptoms of clinical depression, double the rate of similar mothers who were not forced from their homes. Even after years pass, evicted mothers are less happy, energetic, and optimistic than their peers. 
 <br />
 <br />
 When several patients committed suicide in the days leading up to their eviction, a group of psychiatrists published a letter in Psychiatric Services, identifying eviction as a “significant precursor of suicide.” The letter emphasized that none of the patients were facing homelessness, leading the psychiatrists to attribute the suicides to eviction itself. “Eviction must be considered a traumatic rejection,” they wrote, “a denial of one’s most basic human needs, and an exquisitely shameful experience.” Suicides attributed to evictions and foreclosures doubled between 2005 and 2010, years when housing costs soared. 18 Eviction even affects the communities that displaced families leave behind. Neighbors who cooperate with and trust one another can make their streets safer and more prosperous. But that takes time. Efforts to establish local cohesion and community investment are thwarted in neighborhoods with high turnover rates. 
 <br />
 <br />In this way, eviction can unravel the fabric of a community, helping to ensure that neighbors remain strangers and that their collective capacity to combat crime and promote civic engagement remains untapped. 19 Milwaukee neighborhoods with high eviction rates have higher violent crime rates the following year, even after controlling for past crime rates and other relevant factors. 20 Losing your home and possessions and often your job; being stamped with an eviction record and denied government housing assistance; relocating to degrading housing in poor and dangerous neighborhoods; and suffering from increased material hardship, homelessness, depression, and illness—this is eviction’s fallout. Eviction does not simply drop poor families into a dark valley, a trying yet relatively brief detour on life’s journey. 
<br />
<br />
It fundamentally redirects their way, casting them onto a different, and much more difficult, path. Eviction is a cause, not just a condition, of poverty. Eviction affects the old and the young, the sick and able-bodied. But for poor women of color and their children, it has become ordinary. Walk into just about any urban housing court in America, and you can see them waiting on hard benches for their cases to be called. 

<br />
<br />
Among Milwaukee renters, over 1 in 5 black women report having been evicted in their adult life, compared with 1 in 12 Hispanic women and 1 in 15 white women. 21 Most evicted households in Milwaukee have children living in them, and across the country, many evicted children end up homeless. The substandard housing and unsafe neighborhoods to which many evicted families must relocate can degrade a child’s health, ability to learn, and sense of selfworth. 22 And if eviction has lasting effects on mothers’ depression, sapping their energy and happiness, then children will feel that chill too. Parents like Arleen and Vanetta wanted to provide their children with stability, but eviction ruined that, pulling kids in and out of school and batting them from one neighborhood to the next. When these mothers finally did find another place to live, they once again began giving landlords most of their income, leaving little for the kids. Families who spend more on housing spend less on their children. 23 Poor families are living above their means, in apartments they cannot afford. The thing is, those apartments are already at the bottom of the market. 23 Our cities have become unaffordable to our poorest families, and this problem is leaving a deep and jagged scar on the next generation. — All this suffering is shameful and unnecessary. Because it is unnecessary, there is hope. These problems are neither intractable nor eternal. A different kind of society is possible, and powerful solutions are within our collective reach. But those solutions depend on how we answer a single question: do we believe that the right to a decent home is part of what it means to be an American? The United States was founded on the noble idea that people have “certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness.” Each of these three unalienable rights—so essential to the American character that the founders saw them as God-given—requires a stable home.
<br />
<br /> Life and home are so intertwined that it is almost impossible to think about one without the other. The home offers privacy and personal security. It protects and nurtures. 
<br />
<br />
The ideal of liberty has always incorporated not only religious and civil freedoms but also the right to flourish: to make a living however one chooses, to learn and develop new skills. A stable home allows us to strive for self-reliance and personal expression, to seek gainful employment and enjoy individual freedoms. And happiness? It was there in the smile that flashed across Jori’s face when Arleen was able to buy him a new pair of sneakers, in the church hymn Larraine hummed when she was able to cook a nice meal, in the laughter that burst out of the Hinkstons’ house after a good prank. The pursuit of happiness undeniably includes the pursuit of material well-being: minimally, being able to secure basic necessities. It can be overwhelming to consider how much happiness has been lost, how many capabilities snuffed out, by the swell of poverty in this land and our collective decision not to provide all our citizens with a stable and decent place to live. We have affirmed provision in old age, twelve years of education, and basic nutrition to be the right of every citizen because we have recognized that human dignity depends on the fulfillment of these fundamental human needs. And it is hard to argue that housing is not a fundamental human need. Decent, affordable housing should be a basic right for everybody in this country. The reason is simple: without stable shelter, everything else falls apart. — How can we deliver on this obligation? 
<br />
<br />
The good news is that much has already been accomplished. America has made impressive strides over the years when it comes to housing. In generations past, the poor crowded into wretched slums, with many apartments lacking toilets, hot water, heat, or windows. 25 Death and disease were rampant. Over the generations, the quality of housing improved dramatically. And to address the problem of affordability, bold and effective programs were developed. In the middle part of the twentieth century, housing was at the forefront of the progressive agenda. High-rise housing projects were erected to replace slums, sometimes in a single, massive sweep. “Cutting the ribbon for a new public housing project was an occasion to celebrate,” the late housing economist Louis Winnick remembered. “Big-city mayors and aldermen trolled for votes by pledging a towering public housing project for the ward.” 
<br />
<br />When public housing residents saw their apartments—all airy and new, nested in complexes surrounded by expansive grassy fields and playgrounds—they were thrilled. “It is a very beautiful place,” one said, “like a big hotel resort.” 26 But soon the great towers erected to replace slums became slums themselves. 
<br />
<br />
After politicians choked off funding, public housing fell into a miserable state of disrepair. Broken windows, plumbing, and elevators stayed that way; outside, sewer openings were left uncovered and trash piled up. Families who could move did, leaving behind the city’s poorest residents. Soon, public housing complexes descended into chaos and violence. It got to the point where the police refused to go to St. Louis’s Pruitt-Igoe Towers, which would be demolished in front of a televised audience only eighteen years after the first residents moved in. 
<br />
<br />
Across the United States, the wrecking ball and dynamite stick visited other infamous housing projects, such as Chicago’s Robert Taylor Homes and Atlanta’s McDaniel-Glenn Homes—joyless towers casting shadows over segregated and desolate areas of their cities. Given what the projects had become, blowing them up was not only the cheaper option; it was the most humane one, like bulldozing a house in which some unspeakable thing had once transpired. 27 Out of this rubble, the voucher program sprung to life. Whatever else vouchers were, they were not Pruitt-Igoe or Robert Taylor or all the other public housing complexes that had come to be synonymous with urban violence, bitter poverty, and policy failure. Today, the federally funded Housing Choice Voucher Program helps families secure decent housing units in the private rental market. Serving over 2.1 million households, this program has become the largest housing subsidy program for low-income families in the United States. An additional 1.2 million families live in public housing. 28 Cities such as Philadelphia, Seattle, and Oakland have reimagined public housing, often as low-rise, attractive buildings dispersed over several neighborhoods. By and large, both public housing residents and voucher holders pay only 30 percent of their income on rent, with government funds covering the remaining costs. 29 Public initiatives that provide low-income families with decent housing they can afford are among the most meaningful and effective anti-poverty programs in America. Not every public housing resident or voucher holder is poor—many are elderly or disabled; others have modest incomes—but every year rental assistance programs lift roughly 2.8 million people out of poverty. These programs reduce homelessness and allow families to devote more resources to health care, transportation—and food. 30 When families finally receive housing vouchers after years on the waiting list, the first place many take their freed-up income is to the grocery store. They stock the refrigerator and cupboards. Their children become stronger, less anemic, better nourished. 31 But the majority of poor families aren’t so lucky, and their children— children like Jori, Kendal, and Ruby—are not getting enough food because the rent eats first. 
<br /> 
<br />
In 2013, 1 percent of poor renters lived in rent-controlled units; 15 percent lived in public housing; and 17 percent received a government subsidy, mainly in the form of a rent-reducing voucher. The remaining 67 percent—2 of every 3 poor renting families—received no federal assistance. 32 This drastic shortfall in government support, coupled with rising rent and utility costs alongside stagnant incomes, is the reason why most poor renting families today spend most of their income on housing. 33 Imagine if we didn’t provide unemployment insurance or Social Security to most families who needed these benefits. Imagine if the vast majority of families who applied for food stamps were turned away hungry. And yet this is exactly how we treat most poor families seeking shelter. — A problem as big as the affordable-housing crisis calls for a big solution. It should be at the top of America’s domestic-policy agenda—because it is driving poor families to financial ruin and even starting to engulf families with moderate incomes. Today, over 1 in 5 of all renting families in the country spends half of its income on housing. 33 America can and should work to make its cities livable again. Meaningful change comes in various shapes and sizes. Some solutions are slow-going and costly, especially those involving fundamental reform. Other solutions, smaller ones, are more immediately feasible. Consider the courts. Legal aid to the poor has been steadily diminishing since the Reagan years and was decimated during the Great Recession. The result is that in many housing courts around the country, 90 percent of landlords are represented by attorneys, and 90 percent of tenants are not. 35 Low-income families on the edge of eviction have no right to counsel. But when tenants have lawyers, their chances of keeping their homes increase dramatically. 36 Establishing publicly funded legal services for low-income families in housing court would be a cost-effective measure that would prevent homelessness, decrease evictions, and give poor families a fair shake. In the 1963 landmark case Gideon v. Wainwright, the Supreme Court unanimously established the right to counsel for indigent defendants in criminal cases on the grounds that a fair trial was impossible without a lawyer. 
<br />
<br />
Eighteen years later, the court heard the case of Abby Gail Lassiter, a poor black North Carolinian, who appeared without counsel at a civil trial that resulted in her parental rights being terminated. This time, a divided court ruled that defendants had a right to counsel only when they risked losing their physical liberty. Incarceration is a misery, but the outcomes of civil cases also can be devastating. Just ask Ms. Lassiter. Good lawyers would raise defenses tenants often don’t, because they either are unaware of them or, like Arleen, are too nervous and intimidated to mount a strong argument. They would curb frivolous evictions and unchecked abuses and help prevent tenants from signing bad stipulations. 
<br />
<br />If it weren’t so easy to evict someone, tenants like Doreen and Patrice could report dangerous or illegal conditions without fearing retaliation.
<br /> 
<br />
 If tenants had lawyers, they wouldn’t need to go to court. They could go to work or stay home with their children while their attorney made their case. And their case would actually be made. Courts have shown little interest in addressing the fact that the majority of tenants facing eviction never show up. If anything, they have come to depend on this because each day brings a pile of eviction cases, and the goal of every person working in housing court, no matter where their sympathies lie, is just to get through the pile because the next day another pile will be there waiting. The principle of due process has been replaced by mere process: pushing cases through. Tenant lawyers would change that. This would cost money, not only in attorney salaries, but also in the hiring of more commissioners, judges, and clerks to handle the business of justice. Every housing court would need to be adequately funded so that it could function like a court, instead of an eviction assembly line: stamp, stamp, stamp. It would be a worthwhile investment in our cities and children. 
 
 <br />
 <br />
 Directing aid upstream in the form of a few hours of legal services could lower costs downstream. For example, a program that ran from 2005 to 2008 in the South Bronx provided more than 1,300 families with legal assistance and prevented eviction in 86 percent of cases. It cost around $450,000, but saved New York City more than $700,000 in estimated shelter costs alone. 37 The consequences of eviction are many—and so are its burdens on the public purse. 38 
 <br />The right to counsel in civil matters has been established around the world: not just in France and Sweden but also in Azerbaijan, India, Zambia, and many other countries we like to think of as less progressive than our own. 39 If America extended the right to counsel in housing court, it would be a major step on the path to a more fair and equitable society. But it would not address the underlying source of America’s eviction epidemic: the rapidly shrinking supply of affordable housing. — If we acknowledge that housing is a basic right of all Americans, then we must think differently about another right: the right to make as much money as possible by providing families with housing—and especially to profit excessively from the less fortunate. Since the founding of this country, a long line of American visionaries have called for a more balanced relationship, one that protects people from the profit motive, “not to destroy individualism,” in Franklin D. Roosevelt’s words, “but to protect it.” 40 Child labor laws, the minimum wage, workplace safety regulations, and other protections we now take for granted came about when we chose to place the well-being of people above money. There are losers and winners. There are losers because there are winners. “Every condition exists,” Martin Luther King Jr. once wrote, “simply because someone profits by its existence. This economic exploitation is crystallized in the slum.” 41
 <br />
 <br /> Exploitation. Now, there’s a word that has been scrubbed out of the poverty debate. 42 It is a word that speaks to the fact that poverty is not just a product of low incomes. It is also a product of extractive markets. Boosting poor people’s incomes by increasing the minimum wage or public benefits, say, is absolutely crucial. 
 <br />
 <br />
 But not all of those extra dollars will stay in the pockets of the poor. Wage hikes are tempered if rents rise along with them, just as food stamps are worth less if groceries in the inner city cost more— and they do, as much as 40 percent more, by one estimate. 43 Poverty is twofaced—a matter of income and expenses, input and output—and in a world of exploitation, it will not be effectively ameliorated if we ignore this plain fact. History testifies to this point. When the American labor movement rose up in the 1830s to demand higher wages, landed capital did not lock arms with industrial capital. Instead landlords rooted for the workers because higher wages would allow them to collect higher rents. History repeated itself 100 years later, when wage gains that workers had made through labor strikes were quickly absorbed by rising rents. In the interwar years, the industrial job market expanded, but the housing market, especially for blacks, did not, allowing landlords to recoup workers’ income gains. Today, if evictions are lowest each February, it is because many members of the city’s working poor dedicate some or all of their Earned Income Tax Credit to pay back rent. In many cases, this annual benefit is as much a boost to landlords as to lowincome working families. 44 In fixating almost exclusively on what poor people and their communities lack—good jobs, a strong safety net, role models—we have neglected the critical ways that exploitation contributes to the persistence of poverty. We have overlooked a fact that landlords never have: there is a lot of money to be made off the poor. 45 The ’hood is good. Exploitation thrives when it comes to the essentials, like housing and food. Most of the 12 million Americans who take out high-interest payday loans do so not to buy luxury items or cover unexpected expenses but to pay the rent or gas bill, buy food, or meet other regular expenses. <br /> <br /> Payday loans are but one of many financial techniques—from overdraft fees to student loans for for-profit colleges—specifically designed to pull money from the pockets of the poor. 46 If the poor pay more for their housing, food, durable goods, and credit, and if they get smaller returns on their educations and mortgages (if they get returns at all), then their incomes are even smaller than they appear. This is fundamentally unfair. 
 <br />
 <br />Those who profit from the current situation—and those indifferent to it —will say that the housing market should be left alone to regulate itself. They don’t really mean that. Exploitation within the housing market relies on government support. It is the government that legitimizes and defends landlords’ right to charge as much as they want; that subsidizes the construction of high-end apartments, bidding up rents and leaving the poor with even fewer options; that pays landlords when a family cannot, through onetime or ongoing housing assistance; that forcibly removes a family at landlords’ request by dispatching armed law enforcement officers; and that records and publicizes evictions, as a service to landlords and debt collection agencies. Just as the police and the prison have worked to triage the ill effects of rising joblessness in the inner city (like social unrest or the growth of the underground economy), civil courts, sheriff deputies, and homeless shelters manage the fallout of rising housing costs among the urban poor and the privatization of the low-income housing market. 47 Landlords like to describe themselves as a special breed. But they are neither alone in making a living off the poor nor are they so different from the rest of us. Large-scale historical and structural changes have given urban landlords the opportunity to make good money, sometimes spectacular money, by providing housing to struggling families at a cost the law has deemed fair and just. <br />
 <br />
 If given the same opportunity, would any of us price an apartment at half of what it could fetch or simply forgive and forget losing thousands of dollars when the rent checks didn’t arrive? Emphasizing the importance of exploitation does not mean haranguing landlords as greedy or heartless. It means uncovering the ironies and inefficiencies that arise when policymakers try to help poor families without addressing the root causes of their poverty. It means trying to understand landlords’ and tenants’ acceptance of extreme inequality—and our own. Regardless of how landlords came to own property—sweat, intelligence, or ingenuity for some; inheritance, luck, or fraud for others—rising rents mean more money for landlords and less for tenants. Their fates are bound and their interests opposed. If the profits of urban landlords were modest, that would be one thing. But often they are not. The annual income of the landlord of perhaps the worst trailer park in the fourth-poorest city in America is 30 times that of his tenants working full-time for minimum wage and 55 times the annual income of his tenants receiving welfare or SSI. There are two freedoms at odds with each other: the freedom to profit from rents and the freedom to live in a safe and affordable home. 48 — There is a way we can rebalance these two freedoms: by significantly expanding our housing voucher program so that all low-income families could benefit from it. What we need most is a housing program for the unlucky majority—the millions of poor families struggling unassisted in the private market—that promotes the values most of us support: security, fairness, and equal opportunity. A universal housing voucher program would carve a middle path between the landlord’s desire to make a living and the tenant’s desire, simply, to live. The idea is simple. Every family below a certain income level would be eligible for a housing voucher. <br /> <br />They could use that voucher to live anywhere they wanted, just as families can use food stamps to buy groceries virtually anywhere, as long as their housing was neither too expensive, big, and luxurious nor too shabby and run-down. Their home would need to be decent, modest, and fairly priced. 
 <br />
 <br />
 Program administrators could develop fine-grained analyses, borrowing from algorithms and other tools commonly used in the private market, to prevent landlords from charging too much and families from selecting more housing than they need. The family would dedicate 30 percent of their income to housing costs, with the voucher paying the rest. A universal voucher program would change the face of poverty in this country. Evictions would plummet and become rare occurrences. Homelessness would almost disappear. Families would immediately feel the income gains and be able to buy enough food, invest in themselves and their children through schooling or job training, and start modest savings.
 <br />
 <br /> They would find stability and have a sense of ownership over their home and community. Universal housing programs have been successfully implemented all over the developed world. In countries that have such programs, every single family with an income below a certain level who meets basic program requirements has a right to housing assistance. Great Britain’s Housing Benefit is available to so many households that a journalist recently reporting on the program asked, “Perhaps it is easier to say who does not get it?” “Indeed,” came the answer. <br />
 This benefit, transferred directly to landlords in most cases, ensures that paying rent does not plunge a family into poverty. The Netherlands’ Housing Allowance operates in a similar way and helps provide good homes to nearly one-third of all its tenants. It has been remarkably successful at housing the country’s poorest citizens. 

 <br />
 <br />
  There is a reason why these countries have come to rely on vouchers. Although vouchers are not everywhere the most efficient option—particularly in expensive cities—they are the best way to deliver a national program.
 <br />
 <br />
  In theory, you could solve the problem by expanding public housing, tax credits, homeownership initiatives, or developer incentives. But each of these options quickly confronts the problem of scale. Vouchers are far more cost-effective than new construction, whether in the form of public housing or subsidized private development. We can’t build our way out. 
  <br />
  <br />Given mounting regulatory and construction costs, offering each low-income family the opportunity to live in public housing would be prohibitively expensive. Even if it weren’t, building that much public housing risks repeating the failures of the past, by drawing the nation’s poorest citizens under the same roof and contributing to racial segregation and concentrated poverty. 50 Would a universal housing program be a disincentive to work? It is a fair and important question. One study has shown that housing assistance leads to a modest reduction in work hours and earnings, but others have found no effect. 
  <br />
  <br /> In truth, the status quo is much more of a threat to self-sufficiency than any housing program could be.
  <br />
  <br /> Families crushed by the high cost of housing cannot afford vocational training or extra schooling that would allow them to acquire new skills; and many cannot stay in one place long enough to hold down the same job. Affordable housing is a human-capital investment, just like job programs or education, one that would strengthen and steady the American workforce. By and large, the poor do not want some small life. They don’t want to game the system or eke out an existence; they want to thrive and contribute: to become nurses (that was Vanetta’s dream) or run their own charities (that was Arleen’s). A stable home would extend to them the opportunity to realize those dreams. <br /> <br />
  Landlords in most states are not obligated to accept families with housing vouchers, and many don’t because they shun extra building-code mandates or the administrative hassle. A universal voucher program would take their concerns seriously. Some building codes are critical to maintaining safe and decent housing; others are far less so. 
  <br />
  <br />
  Enforcing a strict building code in apartments where voucher holders live can be an unnecessary burden on landlords and drive up costs. 52 But even if code enforcement and program administration were made much more reasonable and landlord-friendly, some property owners—particularly those operating in prosperous areas—would still turn away voucher holders. They simply don’t want to house “those people.” 
  <br />
  <br />
  If we continue to permit this kind of discrimination, we consign voucher holders to certain landlords who own property in certain neighborhoods. Doing so denies low-income families the opportunity to move into economically healthy and safe neighborhoods and hobbles our ability to promote integration through social policy. Accordingly, a universal voucher program would not only strive to make participation attractive to landlords, it would also mandate participation. 
  <br />
  <br />
  Just as we have outlawed discrimination on the basis of race or religion, discrimination against voucher holders would be illegal under a universal voucher program. A well-designed program would ensure a reasonable rent that rose at the rate of inflation and include flexible provisions allowing landlords to receive a modest rate of return. It would also provide them with steadier rental income, less turnover, and fewer evictions.
  <br />
  <br /> If we are going to house most low-income families in the private rental market, then that market must remain profitable. “The business of housing the poor,” Jacob Riis wrote 125 years ago, “if it is to amount to anything, must be a business, as it was business with our fathers to put them where they are. 
  <br />
  <br />
  As charity, pastime, or fad, it will miserably fail, always and everywhere.” 53 And yet, housing is too fundamental a human need, too central to children’s health and development, too important to expanding economic opportunities and stabilizing communities to be treated as simply a business, a crude investment vehicle, something that just “cashes out.” <br /> <br /> 
  Making a universal housing program as efficient as possible would require regulating costs. Expanding housing vouchers without stabilizing rent would be asking taxpayers to subsidize landlords’ profits. 
  <br />
  <br />
   Today, landlords overcharge voucher holders simply because they can. In distressed neighborhoods, where voucher holders tend to live, market rent is lower than what landlords are allowed to charge voucher holders, according to metropolitan-wide rent ceilings set by program administrators. So the Housing Choice Voucher Program likely costs not millions but billions of dollars more than it should, resulting in the unnecessary denial of help to hundreds of thousands of families. 
   <br />
   <br />In fact, economists have argued that the current housing voucher program could be expanded to serve all poor families in America without additional spending if we prevented overcharging and made the program more efficient. 
   <br />
   <br />Even if we did nothing to make the voucher program more costeffective, we still could afford to offer this crucial benefit to all low-income families in America. In 2013, the Bipartisan Policy Center estimated that expanding housing vouchers to all renting families below the 30th percentile in median income for their area would require an additional $22.5 billion, increasing total spending on housing assistance to around $60 billion. 
   <br />
   <br />
   The figure is likely much less, as the estimate does not account for potential savings the expanded program would bring in the form of preventing homelessness, reducing health-care costs, and curbing other costly consequences of the affordable-housing crisis. 
   <br />
   <br /> It is not a small figure, but it is well within our capacity. We have the money. We’ve just made choices about how to spend it. Over the years, lawmakers on both sides of the aisle have restricted housing aid to the poor but expanded it to the affluent in the form of tax benefits for homeowners. 57 
   <br /> <br />
   Today, housing-related tax expenditures far outpace those for housing assistance. In 2008, the year Arleen was evicted from Thirteenth Street, federal expenditures for direct housing assistance totaled less than $40.2 billion, but homeowner tax benefits exceeded $171 billion. 
   <br /> 
   <br />
   That number, $171 billion, was equivalent to the 2008 budgets for the Department of Education, the Department of Veterans Affairs, the Department of Homeland Security, the Department of Justice, and the Department of Agriculture combined. 58 Each year, we spend three times what a universal housing voucher program is estimated to cost (in total) on homeowner benefits, like the mortgage-interest deduction and the capital-gains exclusion. Most federal housing subsidies benefit families with six-figure incomes. 
   <br />
   <br />If we are going to spend the bulk of our public dollars on the affluent—at least when it comes to housing—we should own up to that decision and stop repeating the politicians’ canard about one of the richest countries on the planet being unable to afford doing more. 
   <br />
   <br />
   If poverty persists in America, it is not for lack of resources. — A universal voucher program is but one potential policy recommendation. Let others come. Establishing the basic right to housing in America could be realized in any number of ways—and probably should be. What works best in New York might fail in Los Angeles. The solution to housing problems in booming Houston or Atlanta or Seattle is not what is most needed in the deserted metropolises of the Rust Belt or Florida’s impoverished suburbs or small towns dotting the landscape. 
   <br />One city must build; another must destroy. 
   <br />
   <br />
   If our cities and towns are rich in diversity—with unique textures and styles, gifts and problems—so too must be our solutions. Whatever our way out of this mess, one thing is certain. This degree of inequality, this withdrawal of opportunity, this cold denial of basic needs, this endorsement of pointless suffering—by no American value is this situation justified. No moral code or ethical principle, no piece of scripture or holy teaching, can be summoned to defend what we have allowed our country to become.
</h3>
<br />
<br />
<br />
        </div>
    )
}

export default Ourwhy;
